### ISSUE TITLE
exec: "--config": executable file not found in $PATH: unknown

### ISSUE THREAD

**Issue by zakwear** [mynaparrot/plugNmeet-server#102]
When you uncomment command: --config "./config.yaml", docker can't find the yaml in the volume. Tried a number of things, can't pinpoint it.

docker-compose:

plugnmeet-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080/tcp"
    volumes:
      - .:/app
      - ../client:/app/client
      - ../recording_files:/app/recording_files
      # mount fonts as read only mood
    #      - /usr/share/fonts/:/usr/share/fonts/:ro
    #      - /etc/fonts/:/etc/fonts/:ro
    #      - /usr/share/fontconfig/:/usr/share/fontconfig/:ro
    #      - /var/cache/fontconfig/:/var/cache/fontconfig/:ro
    depends_on:
      - redis
      - db
      - livekit
    command: --config "./config.yaml"

Result: 

plugNmeet/server$ docker-compose up
Removing server_plugnmeet-api_1
Starting server_redis_1 ... done
Starting server_db_1        ... done
Starting server_etherpad_1  ... done
Recreating server_livekit_1 ... done
Recreating 39a9e8e6bcf1_server_plugnmeet-api_1 ... error

ERROR: for 39a9e8e6bcf1_server_plugnmeet-api_1  Cannot start service plugnmeet-api: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "--config": executable file not found in $PATH: unknown

ERROR: for plugnmeet-api  Cannot start service plugnmeet-api: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "--config": executable file not found in $PATH: unknown
ERROR: Encountered errors while bringing up the project.

**Comment by jibon57** [comment]
Use full path command: `--config "/app/config.yaml"`

**Comment by zakwear** [comment]
Tried that path, didn't work

**Comment by jibon57** [comment]
You can keep that comment. Server will load config.yaml automatically.

**Comment by jibon57** [comment]
If you have custom path then need to edit:
https://github.com/mynaparrot/plugNmeet-server/blob/86421e849177736986eb24dc35f394bb68b424ec/start.sh#L3
I've removed that option in this commit: https://github.com/mynaparrot/plugNmeet-server/commit/86421e849177736986eb24dc35f394bb68b424ec

**Comment by zakwear** [comment]
> You can keep that comment. Server will load config.yaml automatically. Do you have `config.yaml` exist in the directory?

Got it, didn't realize config.yaml was loaded automatically. I thought it might not have because no matter what --node-ip I put into the livekit command, the client can't get its token.
