### ISSUE TITLE
Redirect to a url after user exits a room

### ISSUE THREAD

**Issue by shubhendumadhukar** [mynaparrot/plugNmeet-server#171]
This might be a new feature request, but I would like to redirect a user to a url after the meeting is over or user exits the room. I'm not sure if it's already a feature, I couldn't find a documentation on that.

**Comment by jibon57** [comment]
@shubhendumadhukar thank you. I've added new pull. If you can test then can follow: 
https://github.com/mynaparrot/plugNmeet-client/blob/90a13e34bfcf40924c9332fa4e9800b046794faf/src/login.html#L128

**Comment by shubhendumadhukar** [comment]
Hi @jibon57,

Apologies for the delay in response, I just updated the server, client and sdk to the latest versions, however I don't see the redirection to logout_url happening.



logout_url | string | No | You can put logout URL in where plugNmeet will redirect the users after meeting/session ended.
-- | -- | -- | --




Steps I have followed:
1. Create a new meeting with logout_url in metadata.
2. Join meeting with the generated access token.
3. Go to menu > end meeting.

Expecting to be redirected to the url provided as logout_url, however after I end the meeting, I am shown the page stating a message.
```
Room disconnected
The room has been closed. Code: ROOM_ENDED  
```

**Comment by jibon57** [comment]
Make sure you've updated your server + client in latest version. It will took 5 seconds before redirect

**Comment by shubhendumadhukar** [comment]
My bad. It does work as expected. Thanks!

Is there a justification behind the 5 secs gap?
