### ISSUE TITLE
Token Expiration

### ISSUE THREAD

**Issue by imanimen** [mynaparrot/plugNmeet-server#196]
Hi. I have an issue about token expiration time in the server. When I'm in the meeting and I do refresh the page I encounter this error (401 unauthorized - token epired). Is there any way to fix this issue on the server which I'm running the plugnmeet server? or anything else? like increate token jwt time ttl on the server?
Thank you.

**Comment by jibon57** [comment]
You shouldn't refresh the page, if needed then join again. plugNmeet client will auto refresh token but won't change the url one. This is expected behavior of this system.

**Comment by jibon57** [comment]
You can increase expiration time but not recommend: https://github.com/mynaparrot/plugNmeet-server/blob/271f57d5814c19f7bb2c91888755af1b2ba6035b/config_sample.yaml#L40
