### ISSUE TITLE
Test Server Not Available - Wordpress

### ISSUE THREAD

**Issue by GerryGit** [mynaparrot/plugNmeet-server#208]
Have installed PlugnMeet on Wordpress and would like to test.
Using default settings:
https://demo.plugnmeet.com
plugnmeet
zumyyYWqv7KR2kUqvYdq4z4sXg7XTBD2ljT6
Client load: Remote
I receive the message: app.verification-failed-title
app.token-not-valid
Is this an installation issue?
Have not found any clues how to deal with the problem.

**Comment by jibon57** [comment]
You're trying to access without token. Correct: https://demo.plugnmeet.com/login.html
https://www.plugnmeet.org/docs/api/intro
