### ISSUE TITLE
Access token missing - Access token is require which is missing && user creation

### ISSUE THREAD

**Issue by Muhate** [mynaparrot/plugNmeet-server#210]
Hi all!

As my reading, plugNmeet is going to be so helpful for my needs, I also have tried BBB and OpenMeetings, but plugNmeet seems to be much lightweight., thanks for the team... 

I am sorry if I am asking basic questions, but I am really new with PlugNmeet. I have run the installation successfully according to https://www.plugnmeet.org/docs/installation article. When I try to connect via my custom URL it gives me the message "Access token missing - Access token is require which is missing". From /opt/plugNmeet/log/plugNmeet.log I am getting {"file":"/go/src/app/cmd/server/main.go:58","func":"main.startServer.func1","level":"info","msg":"exit requested, shutting down signal terminated","time":"2023-02-15T07:11:50Z"}
{"file":"/go/src/app/pkg/models/room_service.go:134","func":"github.com/mynaparrot/plugnmeet-server/pkg/models.(*RoomService).EndRoom","level":"error","msg":"twirp error internal: operation cannot be completed","time":"2023-02-15T08:04:03Z"}

I tried to google, but nothing helped me. Can someone help me from here?

The frontend test URL https://plugnmeet.mydomain.com/login.html is OK. But I don't see a way to invite anyone to that room.
Obviously the URL plugnmeet.mydomain.com is not the real URL I am using.

I also would like to know how to create user accounts.

Thanks in advance

**Comment by jibon57** [comment]
Hello,

You will require to use API to connect with server. You can have a look from here: https://www.plugnmeet.org/docs/intro#sdks--tools
https://www.plugnmeet.org/docs/api/intro

Thanks

**Comment by Muhate** [comment]
Hi @jibon57 

Thank you for your response.
 Can you guide on how to do that, I didn't get how to set it up

Thanks

**Comment by Muhate** [comment]
Do you mean I will need to have another application to integrate to plugnmeet to run the meetings and creating the users? And I will need to do that via API?

**Comment by jibon57** [comment]
Yes, at present plugNmeet doesn't have any separated management system. You can easily use WordPress, Joomla or Moodle for this. We've ready solution for those CMS. Of course you can use API to implement your own solution.

**Comment by Muhate** [comment]
Many thanks, I am already working on that.
