### ISSUE TITLE
Custom Ports Configuration Documentation

### ISSUE THREAD

**Issue by ajayalag1974** [mynaparrot/plugNmeet-server#292]
Hi,

I have many services running on my single server taking up many ports, nginx is also being used to proxy various public ports to internal services running on other ports.

I want to manually configure/set each & every port being used by plugNmeet, please share how to go about this.

Thanks

**Comment by jibon57** [comment]
Please use discussion as it's not an issue. Also we recommend you to install plugNmeet in a independent server because it's not only a web application but also a complete pack of conferencing solution.

**Comment by ajayalag1974** [comment]
Hi,

Cannot install it in a independent server because we are using 1 big server to serve all our needs.

SUGGESTION : Please reconsider your decision of forcing users to install on independent server because i have configured various media servers/conference like flashphoner, antmedia, jitsi, etc all together working on same server this was possible only because they provided the ability to customize ports being used, adding a documentation page to set custom ports would be great help.
