### ISSUE TITLE
RE: Installation Script

### ISSUE THREAD

**Issue by fuquanii** [mynaparrot/plugNmeet-server#358]
Dear Jibon57,
Firstly, many thanks for pointing me in the correct location to open a ticket. 
In respect of the issue at hand the installation script seems to fail as it shows a "NodeJS" related deprecation error message (see attachment). Then a few other errors are observed before it goes into this endless stream of "dots" (as pointed out by someone else in an earlier ticket in this forum) that appear when it is trying to start the containers towards the end [making](url) it impossible for the script to finish the installation. I am not a programmer, but I suspect your script may need updating (correct me if I am wrong).

Anyway, as (especially given this is something you did from the goodness of your heart for the community at large) I know that it may require time and effort from you to go back and take a look at your installation script and then bring it up-to-date with any changes in the NodeJS part of your installation process (as that software probably has been updated in itself) so if you do not mind I could contribute $50  via Paypal to you in order to help ease the effort and time it may take you to go back and take a look at your installation script and make any needed changes. Personally, I think what you have done for the community is a commendable thing, so this is the least one can do in return to help encourage your community related work to date.

Thus, if you could take a re-look at your install script and make amendments where necessary, do let me know, and I can simply Paypal you as a way of appreciating your effort.

Thanks 
Fuquan
![scriptError-plugnmeet](https://github.com/mynaparrot/plugNmeet-server/assets/141173168/0f26aafb-ea65-44ab-ae93-5903d641ee47)
![plugnmeet nodejs error2](https://github.com/mynaparrot/plugNmeet-server/assets/141173168/f3216b60-d9ba-4805-a445-2add96e9bb74)

**Comment by jibon57** [comment]
@fuquanii thanks for your report & appreciate your effort. I've push new patch for the installation script, will you please try again? I'll recommend you to try with a clear server.

**Comment by fuquanii** [comment]
Dear Jibon,
The thanks are yours really as although I have not managed to use the product as of yet, but just looking over the work and creative input involved deserves appreciation.
I will try again tomorrow as seeing this update a bit late and still have a few domestic chores to attend to prior to calling it a night. All things being well, tomorrow I will keep you informed.
Do have a pleasant night!
Fuquan

**Comment by fuquanii** [comment]
Dear Jibon57,
Firstly, thanks for the amended script, as it works perfectly/flawlessly.
 However, after installation and setup of the WordPress plugin  I can immediately access the room but, if I happen to reboot the test server on which I have PlugNmeet installed on then the new issue I get is that I keep getting this error ("....HTTP response error code: 503....) when I try to enter the room. From first observation, it happened after I did a reboot of the Ubuntu server after it requested I do so because of a kernal update.
I have uninstalled the plugin and reinstalled it, but still the same issue. The server to which I have WordPress installed with the PlugNmeet plugin is a different server that does itself have SSL and a domain name etc and is normally used for PM lightweight stuff.
Would you by any chance know what could possibly be causing this new issue?
Thanks

**Comment by jibon57** [comment]
@fuquanii you'll require to check haproxy, plugnmeet etc logs to find out the problem. Here nothing to do with installation script or plugnmeet itself. If you find difficult to manage your own server then I'll recommend you to use [plugnmeet.cloud](https://plugnmeet.cloud) which is offering the ready to use solution to avoid server related maintenance troubles.

**Comment by fuquanii** [comment]
Hi Jobon57,
Thanks for the pointer to the "hosted" Saas service I will bear that in mind once I have finished testing it. But in the meantime I noticed that although the docker "Volumes" were there the containers did not show up except that of "Etherpad" as none of the below containers were showing up: Unfortunately I spotted this after I had started a new installation (the one now hanging) but I am sure the script will work on a fresh install of Ubuntu, despite it presently doing the dots thing below (as I tried to do a reinstall) then I can take a look at the docker issue that I later spotted. I will cancel this reinstall with all the endless dots and do a fresh OS install as like I said I am sure the script will work first time as it seems to do that.

That said, on doing a reinstallation I did notice the same issue occurred again with the endless dots but here is the install error message about line 347 that showed up incase it helps: Anyway, I will now do a clean OS install then use the script again.
--------------------------------------------------------
-------------------------------------------------------------------------
Need to get 0 B/31.1 MB of archives.
After this operation, 194 MB of additional disk space will be used.
(Reading database ... 164642 files and directories currently installed.)
Preparing to unpack .../nodejs_20.8.0-1nodesource1_amd64.deb ...
Unpacking nodejs (20.8.0-1nodesource1) over (12.22.9~dfsg-1ubuntu3) ...
dpkg: error processing archive /var/cache/apt/archives/nodejs_20.8.0-1nodesource1_amd64.deb (--unpack):
 trying to overwrite '/usr/include/node/common.gypi', which is also in package libnode-dev 12.22.9~dfsg-1ubuntu3
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/nodejs_20.8.0-1nodesource1_amd64.deb
needrestart is being skipped since dpkg has failed
E: Sub-process /usr/bin/dpkg returned an error code (1)
install.sh: line 347: npm: command not found
ERROR: Bad port
Skipping adding existing rule
Skipping adding existing rule (v6)
Skipping adding existing rule
Skipping adding existing rule (v6)
Skipping adding existing rule
Skipping adding existing rule (v6)
Skipping adding existing rule
Skipping adding existing rule (v6)
Skipping adding existing rule
Skipping adding existing rule (v6)
Skipping adding existing rule
Skipping adding existing rule (v6)
Skipping adding existing rule
Skipping adding existing rule (v6)
Firewall is active and enabled on system startup

Finalizing setup..

Starting etherpad..
[+] Running 1/0
 ✔ Container plugnmeet-etherpad-1  Runnin...                                  0.0s 
.....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

**Comment by jibon57** [comment]
@fuquanii that error not related with script. It's nodejs's package problem.

**Comment by fuquanii** [comment]
Hi Jibon, 
Yes I figured that it has to do with nodejs as you say as like you rightly stated the Script still does work.
The only issue it seems to be having is the docker containers not being able to start after a reboot (or even if you restart docker itself the same issue happens) as they come up for a second then fail to start as you can see from the below docker related info. When you do a clean install, everything works fine until you reboot the server. Only one container (Etherpad) remains in a "starting" state the others refuse to come up:
Thus the question one has to ask is: Is this how it is supposed to behave or is there something wrong with the application itself as should it not be able to survive a server reboot?
Thanks
Fuquan
-------------------
root@plugnmeet:/# docker ps
CONTAINER ID   IMAGE                           COMMAND                  CREATED                  STATUS                                     PORTS                                                                                            NAMES
a8fcabb9f432   mynaparrot/plugnmeet-etherpad   "docker-entrypoint.s…"   Less than a second ago   Up Less than a second (health: starting)                                                                                                    plugnmeet-etherpad-1
69d4098e9234   livekit/livekit-server          "/livekit-server --c…"   Less than a second ago   Up Less than a second (health: starting)                                                                                                    plugnmeet-livekit-1
root@plugnmeet:/# docker ps
CONTAINER ID   IMAGE                           COMMAND                  CREATED         STATUS                            PORTS                                                                                            NAMES
655acc903f35   mynaparrot/plugnmeet-etherpad   "docker-entrypoint.s…"   3 seconds ago   Up 2 seconds (health: starting)                                                                                                    plugnmeet-etherpad-1
root@plugnmeet:/# docker ps -a
CONTAINER ID   IMAGE                           COMMAND                  CREATED         STATUS                            PORTS                                                                                            NAMES
bb2715a11c67   mynaparrot/plugnmeet-etherpad   "docker-entrypoint.s…"   6 seconds ago   Up 4 seconds (health: starting)                                                                                                    plugnmeet-etherpad-1
root@plugnmeet:/#
root@plugnmeet:/# docker ps -al
CONTAINER ID   IMAGE                           COMMAND                  CREATED         STATUS                            PORTS     NAMES
42de588ce328   mynaparrot/plugnmeet-etherpad   "docker-entrypoint.s…"   6 seconds ago   Up 5 seconds (health: starting)             plugnmeet-etherpad-1
root@plugnmeet:/#

**Comment by jibon57** [comment]
@fuquanii I don't think you've read documentation properly to debug. You'll need to access the directory where plugnmeet was installed & manually check the logs. Here what you can do:

```
## navigate to directory
cd /opt/plugNmeet
## stop plugnmeet
systemctl stop plugnmeet
## now manually run docker to see the reason it's not working
docker compose up
```
Also there have logs under `log` directory to check the reason. After finding out the problem you'll have to solve it by yourself.

**Comment by fuquanii** [comment]
Hi Jobon57,
Thanks for that I did check the logs (it's part of the first things one has long been accustomed to doing)  but there were only two lines in there at the time just stating the services had failed, so it was not helpful. Thus, to save time I simply reinstalled the application, so I could do some testing. Anyway, may I ask why you do not have a one time paid version of your solution as more and more people (I included) are becoming very data privacy-sensitive with storing their data on other people's servers ("cloud" so to speak) so it may be a prudent option to incorporate a one time paid version for your product to give those who prefer privacy to be able to utilize your product. You do have your own business related website, so you could easily sell it there. Additionally, that may make it easier for those who are in the so called 3rd world to also see your product as a viable solution for them to implement privately. Privacy is a concern in many other parts of the world.  As well as make it easier for those with connections to possibly then consider acting as resellers of your product, as privacy is a viable sales pitch to many in such locations in positions of influence and authority who are growing weary of uncle tom snooping on their data.

Anyway, let me get back to seeing how this product functions, as still a lot to get done before one can call it a night. Have a nice evening.

**Comment by jibon57** [comment]
@fuquanii we don't have enough resources to provide support individually. When it's come about server's configuration, lot of things need to consider & of course have complexity. Yes, if you've good knowledge or have resources to help then it easier. Anyway you can reach to me privately by email: jibon[@]mynaparrot.com
