### ISSUE TITLE
Access token is require which is missing

### ISSUE THREAD

**Issue by gpoveda** [mynaparrot/plugNmeet-server#404]
Hi, 

I'm sorry, I would like to know how can I fix the issue related to "Access token is require which is missing" when I try to access after a fresh installation.

Everything in server (docker) is well: 

db
etherpad
livekit
plugnmeet-api
livekit-ingress
server-redis 

Also in client:

webpack 5.89.0 compiled successfully in 83542 ms
No errors found.

Im not sure if I need to include some "key" from config server in some file from the client files ?

I really appreciate all your help.

Thanks

**Comment by jibon57** [comment]
Please follow: https://www.plugnmeet.org/docs/api/intro
Or to direct access login page: https://your-pnm.com/login.html

**Comment by gpoveda** [comment]
Hi @jibon57 

Thank you very much for your quick response. I have already solve it thanks your advise. Im sorry , I have another question: do you know how can I set up SSL on a docker installation. I can see you have previously explained for stand alone installation with haproxy. Im using this --> https://www.plugnmeet.org/docs/developer-guide/setup-development/

P.S: I dont know is better move this message to the discussion session.


Thank you very much
