### ISSUE TITLE
When a participant exits, the moderator has a white screen

### ISSUE THREAD

**Issue by ddd793** [mynaparrot/plugNmeet-server#468]
Hello.

My system works with Docker (containers - redis, mariadb, livekit, livekit-ingress, plugnmeet-api).
Version - Server: v1.5.14; Client: v1.5.14.
The system is configured according to the instructions from the documentation.

Yesterday, I attempted to upgrade the system to the latest release, version 1.5.15, but I encountered an issue. 
When a participant left the conference, the moderator experienced a blank screen. 
I recorded the incident on video, with the moderator on the left and the participant on the right. 

There is no such issue in version 1.5.14.

Why might this problem occur?

https://github.com/mynaparrot/plugNmeet-server/assets/125999755/b1ad4913-ba3a-4e8a-82da-5e1e41335697

**Comment by jibon57** [comment]
@ddd793 is it possible you to test this commit: https://github.com/mynaparrot/plugNmeet-client/commit/9441c4f38c8b4c64acb208f7e68127da4212dc4b?

**Comment by jibon57** [comment]
Or you can test from: https://demo.plugnmeet.com/login.html

**Comment by jibon57** [comment]
fix: https://github.com/mynaparrot/plugNmeet-client/releases/tag/v1.5.16

**Comment by ddd793** [comment]
It helped. Thanks
