### ISSUE TITLE
The parameter "whiteboard_features" => "preload_file" does not work in plugNmeet PHP SDK

### ISSUE THREAD

**Issue by AlexanderAVV** [mynaparrot/plugNmeet-server#472]
"whiteboard_features" => array(
    "allowed_whiteboard" => true,
    "preload_file" => "https://dvrp.ru/sert.pdf"
)

When specifying a value, this file is not loaded in Whiteboard. The file is present on the server and is accessible without redirection. How to solve this problem?

**Comment by jibon57** [comment]
For me it was perfect
![image](https://github.com/mynaparrot/plugNmeet-server/assets/6080277/26c634fb-749c-4138-a60b-7fb035b3b1a6)

if still do not work then you should check your server's log.

**Comment by AlexanderAVV** [comment]
Thanks for your reply. Where can I view the error log on the server where plugNmeet is installed?
