### ISSUE TITLE
mynaparrot/plugnmeet-server constantly restarts

### ISSUE THREAD

**Issue by johncarterofmars** [mynaparrot/plugNmeet-server#495]
Hello. I have an Ubuntu 22.04 VM on Proxmox with a 50GB HD, 6 cores, and 5GB of mem. I didn't install the recorder. I used the bash script to install and the scripts gets to the end where the containers are starting. The dots going across never stop even after 4 hours. I stopped the script and checked the containers. The mynaparrot/plugnmeet-server container is in a constant state of restarting every 1 minute and never actually starts. 

This is the error from the Docker logs:
```
Jun 06 18:14:15 plugnmeet dockerd[918]: time="2024-06-06T18:14:15.223906317Z" level=info msg="ignoring event" container=daa634c72cd7567a9e711a3678f5430afce8f1b5821ac34b25f50c214a0c64ee module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
```
On a lark, I ran the upgrade script and get a different error: 
```
[2024-06-06T18:10:17.894] [ERROR] settings - Can not perform Etherpad update check: AggregateError
livekit-1  | 2024-06-06T18:10:15.720Z	WARN	livekit	rtcconfig/ip.go:272	could not validate external IP	{"ip": "xxx.xxx.xxx.xxx", "error": "context canceled"}
```
(IP removed)

Ports are forwarded and certbot worked correctly. If I go to the URL from the outside, I do get an error 503 Service unavailable. 

Any suggestions?
Thank you.

**Comment by jibon57** [comment]
You can try to run docker compose manually to check the actual reason. Navigate to `/opt/plugNmeet` and run
```bash
docker compose
```
Also you can check logs from `log` directory.

**Comment by johncarterofmars** [comment]
Thank you. 
Here is what the log reports:
```
{
  "file": "/go/src/app/cmd/server/main.go:38",
  "func": "main.main",
  "level": "fatal",
  "msg": "Error 1045 (28000): Access denied for user 'plugnmeet'@'localhost' (using password: YES)",
  "time": "2024-06-07T19:04:29Z"
}

**Comment by jibon57** [comment]
Error is clear `Error 1045 (28000): Access denied for user 'plugnmeet'@'localhost' (using password: YES)`. Check you MariaDB server to figure it out.

**Comment by johncarterofmars** [comment]
Thank you. I would say one thing. This is using the install script on a fresh install of Ubuntu 22.04, just as reference in case others say anything.
