### ISSUE TITLE
Recording didn't start 

### ISSUE THREAD

**Issue by hadyk77** [mynaparrot/plugNmeet-server#506]
Firstly, I would like to extend my heartfelt thanks for the tremendous effort and dedication you have invested in this project. Your work is greatly appreciated.

I am currently experiencing an issue with recording sessions. Whenever I attempt to record a session, I receive a message stating "record didn't start," yet an MP4 file is still saved in the recording_files directory.
Could you please provide guidance on how to resolve this issue? Here are some additional details that might help
<img width="1375" alt="Screenshot 2024-06-26 at 8 14 01 PM" src="https://github.com/mynaparrot/plugNmeet-server/assets/36902888/9db245b2-9663-4bce-937d-edc496e34a06">

**Comment by german2209** [comment]
I can confirm this error.
It works for local recording but not for cloud recording.
Where can I find the recordings folder to check if there is a mp4 file on my server?

**Comment by hadyk77** [comment]
> I can confirm this error. It works for local recording but not for cloud recording. Where can I find the recordings folder to check if there is a mp4 file on my server?

you should have a recording_files folder where records is stored and also i found the issue it was i miss key in record config.yaml file

**Comment by hadyk77** [comment]
@jibon57 webhook endpoint is not receiving any events any help please ?

**Comment by jibon57** [comment]
You'll have to check logs from recorder e.g. `recorder/logs` to find the problem. Or

```cmd
journalctl -u plugnmeet-recorder@main --no-pager -n 100
journalctl -u plugnmeet-recorder@websocket --no-pager -n 100
```
