### ISSUE TITLE
db / MQ abstraction 

### ISSUE THREAD

**Issue by gedw99** [mynaparrot/plugNmeet-server#523]
SQLC supports mariadb, as well as SQLite.

https://github.com/sqlc-dev/sqlc/tree/main/examples/authors

https://github.com/mynaparrot/plugnmeet-protocol/blob/main/go.mod#L9 would also need to be adapted.

---

The same is true for Redis. NATS Jetstream is able to replace redid easily and can run embedded or non embedded or a DC cluster or a Global multi DC global cluster. Its all built in.

**Comment by jibon57** [comment]
Hi,

We've plan to use https://gorm.io/ in near future.

Thanks

**Comment by jibon57** [comment]
https://github.com/mynaparrot/plugNmeet-server/pull/550
