### ISSUE TITLE
Docker error

### ISSUE THREAD

**Issue by Char99s** [mynaparrot/plugNmeet-server#548]
Hello again, I recently downloaded plugNmeet on my ubuntu server on vbox and it is running fine. I am able to connect from a nextjs app running on my windows to the plugnmeet server running on the vbox instance. i was able to fetch client files but not create room. I get the following error when I do so:

{
  status: false,
  msg: 'Error: twirp error internal: failed to do request: Post "http://host.docker.internal:7880/twirp/livekit.RoomService/CreateRoom": dial tcp: lookup host.docker.internal on 127.0.0.11:53: no such host',
  roomInfo: undefined
}

Thanks for the support!

**Comment by Char99s** [comment]
![Screenshot 2024-08-19 124841](https://github.com/user-attachments/assets/8c610569-8ceb-474c-bfd4-6e19269a0da0)

I also get the following errors i dont know if its related

**Comment by jibon57** [comment]
System was trying to connect `host.docker.internal`. I don't think that's the correct host for your case. Try to replace it with proper IP/hostname.

**Comment by Char99s** [comment]
> System was trying to connect `host.docker.internal`. I don't think that's the correct host for your case. Try to replace it with proper IP/hostname.

The thing is that I am able to connect to the server from my windows. I also just installed docker on the server and ran plugNmeet server following the docs. So the error is internal from plugNmeet itself and I can't find where it's from. I did the same steps on WSL and it worked. Maybe it's because the server is on VBOX?

**Comment by Char99s** [comment]
Fixed by adding the following to the services in the docker-compose.yaml :

 extra_hosts:
    - "host.docker.internal:host-gateway"

seems like it's needed when using docker on Linux
