### ISSUE TITLE
PlugNmeet client integration into custom Next.js app

### ISSUE THREAD

**Issue by Char99s** [mynaparrot/plugNmeet-server#577]
Hello, I was trying to integrate the client project into my next.js app. when i call the get client files endpoint i am getting the following response: `{ status: true, msg: 'success', css: null, js: null }`

Any idea why this might be happening?

**Comment by jibon57** [comment]
Hi,

You'll need to build client first by `pnpm run build`

**Comment by Char99s** [comment]
> Hi,
> 
> You'll need to build client first by `pnpm run build`

Hi Jibon thank you for your answers. I have a nextjs app where it connects to the plugnmeet server and i fetch the client files. I am wondering are these client files enough to run the whole ui and funcitonalities built in? is there any ts/js tutorial on that matter? Thank you!

**Comment by jibon57** [comment]
I think you asked the same question here: https://github.com/mynaparrot/plugNmeet-server/discussions/542
