### ISSUE TITLE
install script is not working

### ISSUE THREAD

**Issue by jhjacobs81** [mynaparrot/plugNmeet-server#579]
So following this page: https://www.plugnmeet.org/docs/installation
i created an Ubuntu 22.04 LTS VPS with nothing on it.
i then execute: `sudo su -c "bash <(wget -qO- https://raw.githubusercontent.com/mynaparrot/plugNmeet-install/main/install.sh)" root`
Which installs a bunch of software, add docker containers etc. it runs all the way up untill these error messages:
```

haproxy[5744]: backend bk_plugnmeet_server has no server available!


Broadcast message from systemd-journald@domain.tld (Tue 2024-10-29 15:50:17 UTC):

haproxy[5744]: backend bk_plugnmeet_server has no server available!


Broadcast message from systemd-journald@domain.tld (Tue 2024-10-29 15:50:18 UTC):

haproxy[5744]: backend bk_etherpad has no server available!


Broadcast message from systemd-journald@domain.tld (Tue 2024-10-29 15:50:18 UTC):

haproxy[5744]: backend bk_etherpad has no server available!


Broadcast message from systemd-journald@domain.tld (Tue 2024-10-29 15:50:18 UTC):

haproxy[5744]: backend bk_etherpad has no server available!


Broadcast message from systemd-journald@domain.tld (Tue 2024-10-29 15:50:18 UTC):

haproxy[5744]: backend bk_etherpad has no server available!

.
Broadcast message from systemd-journald@domain.tld (Tue 2024-10-29 15:50:18 UTC):

haproxy[5744]: backend bk_ingress has no server available!


Broadcast message from systemd-journald@domain.tld (Tue 2024-10-29 15:50:18 UTC):

haproxy[5744]: backend bk_ingress has no server available!


Broadcast message from systemd-journald@domain.tld (Tue 2024-10-29 15:50:18 UTC):

haproxy[5744]: backend bk_ingress has no server available!


Broadcast message from systemd-journald@domain.tld (Tue 2024-10-29 15:50:18 UTC):

haproxy[5744]: backend bk_ingress has no server available!


Broadcast message from systemd-journald@domain.tld (Tue 2024-10-29 15:50:19 UTC):

haproxy[5744]: proxy rtmp has no server available!


Broadcast message from systemd-journald@domain.tld (Tue 2024-10-29 15:50:19 UTC):

haproxy[5744]: proxy rtmp has no server available!


Broadcast message from systemd-journald@domain.tld (Tue 2024-10-29 15:50:19 UTC):

haproxy[5744]: proxy rtmp has no server available!


Broadcast message from systemd-journald@domain.tld (Tue 2024-10-29 15:50:19 UTC):

haproxy[5744]: proxy rtmp has no server available!
```

After which follows an endless stream of '............' and the server shows only:
503 Service Unavailable
No server is available to handle this request. 

in the browser.

**Comment by jhjacobs81** [comment]
trying it on Debian 12 isnt working either :(

![image](https://github.com/user-attachments/assets/3b69f493-111b-4e48-886a-499c540ee8e0)

**Comment by jhjacobs81** [comment]
For future reference: this was due to 3 CPU's instead of the minimal 4. idealy, the script would report this at the start and not continue at all, but alas!

**Comment by sanyaade-teachings** [comment]
> For future reference: this was due to 3 CPU's instead of the minimal 4. idealy, the script would report this at the start and not continue at all, but alas!


I strongly believe this issue needs to be investigated or improve the script's querying the O/S and system core. The same issue as stated above happens on a system with:
OS: Ubuntu 24.04
No of Cores 2x10 core CPUs (20 cores)
RAM: 120GB PC3 1600Mhz
Make: Dell R630

God blesses!!!

Regards
