### ISSUE TITLE
Removey Haproxy (non Haproxy dependent) and own proxy (e.g. Caddy Server or other)

### ISSUE THREAD

**Issue by sanyaade-teachings** [mynaparrot/plugNmeet-server#626]
Hi Everyone,

I setup plugNmeet Server but I am having issues regarding  ==> "**Invalid Host header**"  when I try to enter the website
I have followed all your instruction including troubleshooting but nothing work

I have Caddy Server running as proxy-server, since it is easy to configure and maintain than haproxy for me.

Please kindly provide guide on how to setup plugNmeet without Haproxy or how to disable haproxy. 

Many thanks for your time. Any help or pointer will be highly appreciated.

Hear from you soon

God blesses!!!

Regards

**Comment by jibon57** [comment]
plugNmeet doesn't depend on Haproxy. You can install plugNmeet anywhere without using any proxy. You'll need to debug by yourself to make it working. We're using installation script so that user can easily get things working.

**Comment by sanyaade-teachings** [comment]
> plugNmeet doesn't depend on Haproxy. You can install plugNmeet anywhere without using any proxy. You'll need to debug by yourself to make it working. We're using installation script so that user can easily get things working.

Got it working but now I am facing a token is required on the login page. 

Any help or pointer on this?

Regards
